main: me.chickenstyle.rewards.Main
name: RewardsGiver
version: 1.0
description: Damage manager for mythicmobs!
api-version: 1.15
commands:
  rewardgiver: 
    aliases: rg
    description: Plugin's main command
